---
- name: install nginx and start
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: install nginx
      apt: 
        name: nginx
        state: present
        update_cache: yes

    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes
