---
- name: Install and Start Nginx
  hosts: all
  become: true  # This uses sudo to install the package

  tasks:
    - name: Ensure Nginx is installed
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
        name: nginx
        state: started
        enabled: true
